version: "3.9"

services:
  potty_db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: db.env
  potty_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - db.env
      - app.env
    depends_on:
      - potty_db