# Generated by Django 3.2.15 on 2022-09-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeeOrPoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_poo', models.BooleanField()),
                ('time', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kid')),
            ],
            options={
                'ordering': ['kid__id', 'time'],
            },
        ),
    ]
