# Generated by Django 3.2.15 on 2022-09-05 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_peeorpoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peeorpoo',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pee_or_poos', to='kids.kid'),
        ),
    ]
